--- # RELEASE.yml
name: Google Apps Script Publish (RELEASE)
on: { push: { tags: ['v[0-9]+.[0-9]+.[0-9]+'] } }
jobs:
  publish-release:
    name: Build/Publish (RELEASE)
    environment:
      name: RELEASE
      url: https://script.google.com/home/projects/1qFMqBXZquMU9CrUnqjp-TRRtAxtDn24zFiqKID3f7pNzKGD23m38bbze/edit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Install Node
        id: node
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Install Dependencies
        id: ci
        run: npm ci --loglevel=error --fund=false
      - name: Load Google Apps Script Secret
        id: secrets
        run: |
          rm -f ~/.clasprc.json
          echo '${{secrets.CLASPRC}}' >> ~/.clasprc.json
      - name: Publish to Google Apps Script
        id: publish
        run: npm run deploy

...
